2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_setup.py:_flush():81] Configure stats pid to 275896
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_setup.py:_flush():81] Loading settings from /home/thiago-bittencourt/.config/wandb/settings
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_setup.py:_flush():81] Loading settings from /home/thiago-bittencourt/fc-projeto-final/wandb/settings
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/thiago-bittencourt/fc-projeto-final/wandb/run-20250625_105950-zxoj546o/logs/debug.log
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/thiago-bittencourt/fc-projeto-final/wandb/run-20250625_105950-zxoj546o/logs/debug-internal.log
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7d7911d67470>
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_init.py:init():831] calling init triggers
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'batch_size': 32, 'epochs': 50, 'learning_rate': 0.1, 'model': 'DCNN08', 'fault_type': 'outer', 'augmentation': 'fft', 'seed': 258, 'multiplyby': 2, '_wandb': {}}
2025-06-25 10:59:50,928 INFO    MainThread:275896 [wandb_init.py:init():872] starting backend
2025-06-25 10:59:51,137 INFO    MainThread:275896 [wandb_init.py:init():875] sending inform_init request
2025-06-25 10:59:51,138 INFO    MainThread:275896 [wandb_init.py:init():883] backend started and connected
2025-06-25 10:59:51,140 INFO    MainThread:275896 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2025-06-25 10:59:51,140 INFO    MainThread:275896 [wandb_init.py:init():956] updated telemetry
2025-06-25 10:59:51,144 INFO    MainThread:275896 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-25 10:59:51,721 INFO    MainThread:275896 [wandb_init.py:init():1032] starting run threads in backend
2025-06-25 10:59:51,773 INFO    MainThread:275896 [wandb_run.py:_console_start():2453] atexit reg
2025-06-25 10:59:51,773 INFO    MainThread:275896 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-25 10:59:51,773 INFO    MainThread:275896 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-25 10:59:51,773 INFO    MainThread:275896 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-25 10:59:51,774 INFO    MainThread:275896 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-25 10:59:51,775 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 10:59:52,149 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 10:59:52,149 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:03,404 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:03,408 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:03,408 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:03,411 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:03,414 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:03,414 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:03,414 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:04,910 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:04,910 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:04,911 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:11,621 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:11,621 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:11,624 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:12,439 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:12,439 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:12,440 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:13,476 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:13,477 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:13,477 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:15,499 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:15,499 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:15,500 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:16,905 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:16,905 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:16,906 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:18,969 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:18,969 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:19,070 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:20,284 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:20,284 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:20,286 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:21,445 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:21,446 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:21,446 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:23,521 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:23,521 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:00:23,823 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-25 11:00:24,940 INFO    MainThread:275896 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-25 11:00:24,940 INFO    MainThread:275896 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-25 11:02:47,022 WARNING MsgRouterThr:275896 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-25 11:02:47,031 INFO    MsgRouterThr:275896 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-25 11:02:47,349 INFO    MainThread:275896 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
